import com.github.triplet.gradle.androidpublisher.ReleaseStatus

plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.plugin.parcelize'
    id 'com.github.triplet.play' version '4.1.1'
}

private def loadLocalProperties() {
    Properties properties = new Properties()
    def localPropertiesFile = project.rootProject.file('local.properties');
    if(!localPropertiesFile.exists()){
        localPropertiesFile.createNewFile();
    }
    properties.load(localPropertiesFile.newDataInputStream())
    return properties
}

def properties = loadLocalProperties();

def applicationVersionName = "1.5.0"
def versionNameList = applicationVersionName.split(/\./)
def powCounter = versionNameList.size()
def versionNumbers = versionNameList.collect{numberString -> numberString.toInteger()}
def applicationVersionCode = versionNumbers.sum{ number ->
    powCounter = powCounter - 1
    (Math.pow(100, powCounter) * number).toInteger()
}

android {
    namespace 'com.taku.kobayashi.refarorsample'
    compileSdk 37
    buildToolsVersion = "37.0.0"
    defaultConfig {
        applicationId "com.taku.kobayashi.refarorsample"
        minSdkVersion 21
        targetSdkVersion 37
        versionCode applicationVersionCode
        versionName applicationVersionName
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        multiDexEnabled true
    }
    signingConfigs {
        release {
            if(!properties.getProperty("RELEASE_STORE_FILE", "").empty){
                storeFile file(properties.getProperty("RELEASE_STORE_FILE", ""))
            }
            storePassword properties.getProperty("RELEASE_STORE_PASSWORD", "")
            keyAlias properties.getProperty("RELEASE_KEY_ALIAS", "")
            keyPassword properties.getProperty("RELEASE_KEY_PASSWORD", "")
        }
    }
    buildTypes {
        release {
            shrinkResources true
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

kotlin {
    jvmToolchain(17)
}

if(!properties.getProperty("GOOGLE_PLAY_SERVICE_ACCOUNT_CREDENTIALS_FILE_PATH", "").empty) {
    play {
        serviceAccountCredentials.set(file(properties.getProperty("GOOGLE_PLAY_SERVICE_ACCOUNT_CREDENTIALS_FILE_PATH", "")))
        track.set("internal")
        artifactDir.set(file("build/outputs/bundle/release/"))
    }
}

dependencies {
    implementation 'androidx.core:core-ktx:1.19.0'
    implementation 'androidx.appcompat:appcompat:1.8.0'
    implementation 'com.google.android.material:material:1.14.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.2'
    implementation 'com.android.installreferrer:installreferrer:2.2'
    implementation 'com.google.android.play:asset-delivery:2.3.0'
    implementation 'com.google.android.play:review:2.0.2'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.3.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.7.0'
}

play {
    def androidDefaultConfig = android.getDefaultConfig()
    if(!properties.getProperty("GOOGLE_PLAY_PUBLISH_API_CONFIG_FILE", "").empty) {
        serviceAccountCredentials = file(properties.getProperty("GOOGLE_PLAY_PUBLISH_API_CONFIG_FILE", ""))
    }
    artifactDir = file("build/outputs/bundle/release/")
    track = "beta"
    releaseStatus = ReleaseStatus.DRAFT
    releaseName = "${androidDefaultConfig.versionCode} (${androidDefaultConfig.versionName})"
}
